/**
 * Forever Studio — scheduled background continuation (server-only).
 *
 * Invoked by the Cloudflare Cron Trigger through the Worker module's
 * `scheduled()` export (generated by the Nitro cloudflare-module preset) via
 * the `cloudflare:scheduled` runtime hook registered in scheduled.plugin.ts.
 * The cron cadence lives in the repository wrangler.jsonc (`triggers.crons`),
 * which Nitro merges into the generated deploy config at build time.
 *
 * Operating contract:
 *   - runs with server-only (service-role) credentials — there is NO public
 *     HTTP endpoint, NO user Auth token, and NO browser session involved;
 *   - claims only explicitly processing-requested Studio jobs whose source
 *     membership is currently active (enforced inside studio_list_due_jobs);
 *   - the Owner/Trusted Publisher upload remains the publication
 *     authorization — the runner adds none of its own;
 *   - performs bounded claim-scoped slices per invocation and never throws:
 *     a failing tick is logged (redacted) and the next cron tick retries.
 */

export async function runStudioScheduledTickSafely(): Promise<void> {
  try {
    const { createStudioDeps } = await import("./deps.server");
    const { runScheduledStudioTick } = await import("./service");
    const summary = await runScheduledStudioTick(createStudioDeps());
    if (summary.due > 0) {
      // Counts only — never job ids, filenames, facts, or paths.
      console.info(
        `[studio-scheduled] due=${summary.due} advanced=${summary.advanced} ` +
          `published=${summary.published} failed=${summary.failed} skipped=${summary.skipped}`,
      );
    }
  } catch (error) {
    const { logStudioFailure } = await import("./errors");
    logStudioFailure("studio_scheduled_tick_failed", error);
  }
}
