[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'ForeverOperator.psm1') -Force
$script:Passed=0;$script:Failed=0
function Test-Case([string]$Name,[scriptblock]$Body){try{&$Body;Write-Host "PASS $Name";$script:Passed++}catch{Write-Host "FAIL $Name :: $($_.Exception.Message)";$script:Failed++}}
function Assert-True($Value,[string]$Message='assertion failed'){if(-not$Value){throw$Message}}
function Assert-Equal($Actual,$Expected,[string]$Message='values differ'){if($Actual-ne$Expected){throw "$Message; actual='$Actual' expected='$Expected'"}}
function Assert-Throws([scriptblock]$Body,[string]$Pattern){try{&$Body;throw'expected exception was not raised'}catch{if($_.Exception.Message-eq'expected exception was not raised'-or$_.Exception.Message-notmatch$Pattern){throw}}}
function Write-Utf8([string]$Path,[string]$Value){$parent=Split-Path $Path;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[IO.File]::WriteAllText($Path,$Value,[Text.UTF8Encoding]::new($false))}
function Run-Git([string]$Directory,[string[]]$Arguments){$result=Invoke-Native 'git.exe' $Arguments $Directory 60 -AllowFailure;if($result.ExitCode){throw"git failed: $($result.Output)"};$result.Summary}

function New-Fixture {
  param([string]$Name,[string]$Target='docs/a.md',[string]$Content="changed`n",[string]$RiskOverride=$null,[string]$Profile='quick',[bool]$CreatePr=$false,[bool]$AutoMerge=$false,[bool]$ConfigAutoMerge=$false,[switch]$LintFailure)
  $base=Join-Path $script:Root $Name;$repo=Join-Path $base 'repo';$bare=Join-Path $base 'origin.git';New-Item -ItemType Directory -Force -Path $repo|Out-Null
  Run-Git $base @('init','--bare','--initial-branch=main',$bare)|Out-Null;Run-Git $repo @('init','--initial-branch=main')|Out-Null;Run-Git $repo @('config','user.name','Fixture Tester')|Out-Null;Run-Git $repo @('config','user.email','fixture@example.invalid')|Out-Null
  Write-Utf8 (Join-Path $repo '.gitignore') "/.forever-factory/`n";Write-Utf8 (Join-Path $repo 'docs/a.md') "base`n";Write-Utf8 (Join-Path $repo 'src/base.ts') "export const base = true;`n"
  Run-Git $repo @('add','--','.gitignore','docs/a.md','src/base.ts')|Out-Null;Run-Git $repo @('commit','-m','fixture base')|Out-Null;Run-Git $repo @('remote','add','origin',$bare)|Out-Null;Run-Git $repo @('push','-u','origin','main')|Out-Null;$sha=Run-Git $repo @('rev-parse','HEAD')
  $targetPath=Join-Path $repo $Target;Write-Utf8 $targetPath $Content;if((Invoke-Native 'git.exe' @('ls-files','--error-unmatch','--',$Target) $repo 30 -AllowFailure).ExitCode -eq 0){$patchText=(Invoke-Native 'git.exe' @('diff','--binary','--',$Target) $repo 60).Output;Run-Git $repo @('checkout','--',$Target)|Out-Null}else{Run-Git $repo @('add','--',$Target)|Out-Null;$patchText=(Invoke-Native 'git.exe' @('diff','--cached','--binary','--',$Target) $repo 60).Output;Run-Git $repo @('reset','--',$Target)|Out-Null;Remove-Item -LiteralPath $targetPath -Force}
  $factory=Join-Path $repo '.forever-factory';foreach($d in 'inbox','worktrees','reports','logs','state'){New-Item -ItemType Directory -Force -Path (Join-Path $factory $d)|Out-Null};$patch=Join-Path $factory 'inbox/task.patch';Write-Utf8 $patch $patchText
  $lintScript=Join-Path $factory 'lint.ps1';Write-Utf8 $lintScript ($(if($LintFailure){"param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$Files)`nexit 9`n"}else{"param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$Files)`nexit 0`n"}))
  $validations=@(@{name='git-diff-check';executable='git.exe';arguments=@('diff','--check')});if($Profile-eq'lint'){$validations=@(@{name='changed-file-lint';executable='powershell.exe';arguments=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$lintScript)})}
  $config=[ordered]@{schemaVersion='0.1';repositoryRoot='..';defaultBranch='main';githubRepository='FixtureOwner/FixtureRepo';patchInbox='inbox';worktreeRoot='worktrees';reportRoot='reports';logRoot='logs';stateRoot='state';validationProfiles=@{quick=$validations;lint=$validations};lintBaseline=@{errorCount=5379};protectedPaths=@('.github/workflows/**','.env*','supabase/migrations/**');binaryPatchesAllowed=$false;highRiskPullRequestsAllowed=$false;autoMerge=$ConfigAutoMerge;maximumRetryCount=3;timeouts=@{commandSeconds=60;githubChecksSeconds=60;githubPollSeconds=1};security=@{maximumFileBytes=1048576}}
  $task=[ordered]@{schemaVersion='0.1';taskId="TASK-$Name";title='Fixture task';patchPath='inbox/task.patch';expectedBaseCommit=$sha;allowedPaths=@('**');forbiddenPaths=@();riskOverride=$RiskOverride;branchName="factory/$Name";commitMessage='test: apply fixture';createPullRequest=$CreatePr;allowAutomaticMerge=$AutoMerge;validationProfile=$Profile}
  $configPath=Join-Path $factory 'operator.config.json';$taskPath=Join-Path $factory 'CURRENT_TASK.json';$config|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $configPath -Encoding utf8;$task|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $taskPath -Encoding utf8
  [pscustomobject]@{Repo=$repo;Factory=$factory;Config=$configPath;Task=$taskPath;Patch=$patch;TaskObject=$task;ConfigObject=$config;Sha=$sha}
}

$script:Root=Join-Path ([IO.Path]::GetTempPath()) ("forever-operator-hardening-"+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $script:Root|Out-Null
try{
  $valid=[pscustomobject]@{schemaVersion='0.1';taskId='TEST-001';title='safe title';patchPath='inbox/a.patch';expectedBaseCommit=('a'*40);allowedPaths=@('docs/**');forbiddenPaths=@();riskOverride=$null;branchName='factory/test';commitMessage='test: safe';createPullRequest=$false;allowAutomaticMerge=$false;validationProfile='quick'}
  Test-Case 'reject task title newline'{$bad=$valid.PSObject.Copy();$bad.title="bad`nvalue";Assert-Throws{Assert-Task $bad}'control'}
  Test-Case 'reject commit message control character'{$bad=$valid.PSObject.Copy();$bad.commitMessage="bad$([char]1)value";Assert-Throws{Assert-Task $bad}'control'}
  Test-Case 'reject branch traversal and Git-special names'{foreach($branch in @('-option','factory/../main','factory//x','factory/x.lock','factory/@{x','factory/x~1')){$bad=$valid.PSObject.Copy();$bad.branchName=$branch;Assert-Throws{Assert-Task $bad}'branchName'}}
  Test-Case 'reject shell metacharacters in branch'{foreach($char in @('&','|',';','>','<','^','%','!','"',"'",'`','(',')')){$bad=$valid.PSObject.Copy();$bad.branchName="factory/a${char}b";Assert-Throws{Assert-Task $bad}'branchName'}}
  $echoScript=Join-Path $script:Root 'echo-argument.ps1';Write-Utf8 $echoScript 'param([string]$Value); [Console]::Write($Value)'
  Test-Case 'native arguments pass metacharacters literally'{$payload='& | ; > < ^ % ! " '' ` ( )';$r=Invoke-Native 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$echoScript,$payload) $script:Root 30;Assert-Equal $r.Output $payload}
  Test-Case 'safe command display cannot execute payload'{$marker=Join-Path $script:Root 'injected.txt';$payload="literal & echo owned > $marker";$r=Invoke-Native 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$echoScript,$payload) $script:Root 30;Assert-True(-not(Test-Path -LiteralPath $marker));Assert-Equal $r.Output $payload}
  Test-Case 'npm command resolves without cmd shell'{$r=Invoke-Native 'npm.cmd' @('--version') $script:Root 30;Assert-Equal $r.ExitCode 0;Assert-True($r.Output-match'^\d+\.\d+\.\d+$')}
  Test-Case 'task title and commit metacharacters are accepted as data'{$copy=$valid.PSObject.Copy();$copy.title='Title & | ; > < ^ % ! " '' ` ( )';$copy.commitMessage='test: literal & | ; > < ^ % ! " '' ` ( )';Assert-Task $copy}
  Test-Case 'rendered command and output redact secrets'{$log=Join-Path $script:Root 'redaction.log';$secret='github_token=ghp_abcdefghijklmnopqrstuvwxyz123456';$r=Invoke-Native 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$echoScript,$secret) $script:Root 30 -LogPath $log;$logged=Get-Content -Raw -LiteralPath $log;Assert-True($logged-notmatch'ghp_abcdefghijklmnopqrstuvwxyz');Assert-True($r.Output-match'REDACTED')}
  Test-Case 'risk HIGH cannot downgrade to LOW'{Assert-Equal(Get-Risk @('supabase/migrations/1.sql') '' 'LOW')'HIGH'}
  Test-Case 'risk MEDIUM cannot downgrade to LOW'{Assert-Equal(Get-Risk @('src/widget.ts') '' 'LOW')'MEDIUM'}
  Test-Case 'risk LOW can raise to MEDIUM'{Assert-Equal(Get-Risk @('docs/a.md') '' 'MEDIUM')'MEDIUM'}
  Test-Case 'risk MEDIUM can raise to HIGH'{Assert-Equal(Get-Risk @('src/widget.ts') '' 'HIGH')'HIGH'}

  Test-Case 'integration successful validate-only and unchanged lint baseline'{$f=New-Fixture 'validate';$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;Assert-Equal $r.FinalStatus 'validated' $r.StopReason;Assert-True($r.Lint-match'baseline: 5379');Assert-True(-not(Test-Path (Join-Path $f.Factory 'worktrees/TASK-validate')))}
  Test-Case 'integration changed-file lint passes'{$f=New-Fixture 'lintpass' -Target 'src/base.ts' -Content "export const base = false;`n" -Profile lint;$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;Assert-Equal $r.FinalStatus 'validated' $r.StopReason;Assert-True($r.Lint-match'passed for 1 changed file')}
  Test-Case 'integration patch introduces lint failure'{$f=New-Fixture 'lintfail' -Target 'src/base.ts' -Content "export const broken = ;`n" -Profile lint -LintFailure;$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;Assert-Equal $r.FinalStatus 'stopped';Assert-True($r.StopReason-match'changed-file-lint')}
  Test-Case 'integration patch path escape rejected'{$f=New-Fixture 'escape';$task=Get-Content -Raw $f.Task|ConvertFrom-Json;$task.patchPath='../outside.patch';$task|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $f.Task;$outside=Join-Path $f.Repo 'outside.patch';Copy-Item -LiteralPath $f.Patch -Destination $outside;Assert-Throws{Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch}'Patch path must stay'}
  Test-Case 'integration wrong base commit stops'{$f=New-Fixture 'wrongbase';$task=Get-Content -Raw $f.Task|ConvertFrom-Json;$task.expectedBaseCommit='f'*40;$task|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $f.Task;$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;Assert-Equal $r.FinalStatus 'stopped';Assert-True($r.StopReason-match'base commit does not exist')}

  $script:GitHubActions=@();$adapter={param($Action,$Data)$script:GitHubActions+=$Action;switch($Action){'auth'{$true};'push'{$true};'find-pr'{$null};'create-pr'{'https://example.invalid/pr/1'};'inspect-pr'{[pscustomobject]@{PullRequest=[pscustomobject]@{baseRefName='main';headRefName=$Data.ExpectedBranch;headRefOid=$Data.ExpectedSha;mergeable='MERGEABLE';reviewDecision='APPROVED';statusCheckRollup=@([pscustomobject]@{conclusion='SUCCESS'})};Protection=[pscustomobject]@{required_pull_request_reviews=[pscustomobject]@{required_approving_review_count=1}}}};'merge'{$true}}}
  function New-Adapter([string]$Branch,[scriptblock]$CommitGetter){return{param($Action,$Data)$script:GitHubActions+=$Action;switch($Action){'auth'{$true};'push'{$true};'find-pr'{$null};'create-pr'{'https://example.invalid/pr/1'};'inspect-pr'{$sha=&$CommitGetter;[pscustomobject]@{PullRequest=[pscustomobject]@{baseRefName='main';headRefName=$Branch;headRefOid=$sha;mergeable='MERGEABLE';reviewDecision='APPROVED';statusCheckRollup=@([pscustomobject]@{conclusion='SUCCESS'})};Protection=[pscustomobject]@{required_pull_request_reviews=[pscustomobject]@{required_approving_review_count=1}}}};'merge'{$true}}}.GetNewClosure()}
  Test-Case 'integration LOW-risk PR policy without network'{$f=New-Fixture 'lowpr' -CreatePr $true;$script:CurrentCommit=$null;$a=New-Adapter $f.TaskObject.branchName {Run-Git $f.Repo @('rev-parse',"refs/heads/$($f.TaskObject.branchName)")};$script:GitHubActions=@();$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode create-pr -ConfigFile $f.Config -SkipFetch -GitHubAdapter $a;Assert-Equal $r.FinalStatus 'pr-created' $r.StopReason;Assert-True($script:GitHubActions-notcontains'merge')}
  Test-Case 'integration MEDIUM no auto-merge'{$f=New-Fixture 'medium' -Target 'src/base.ts' -Content "export const base = false;`n" -CreatePr $true -AutoMerge $true -ConfigAutoMerge $true;$a=New-Adapter $f.TaskObject.branchName {Run-Git $f.Repo @('rev-parse',"refs/heads/$($f.TaskObject.branchName)")};$script:GitHubActions=@();$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode create-pr -ConfigFile $f.Config -SkipFetch -GitHubAdapter $a;Assert-Equal $r.Risk 'MEDIUM';Assert-True($script:GitHubActions-notcontains'merge')}
  Test-Case 'integration HIGH stops before push'{$f=New-Fixture 'high' -Target 'src/security/auth.ts' -Content "export const auth = true;`n" -CreatePr $true;$script:GitHubActions=@();$r=Invoke-ForeverOperator -TaskFile $f.Task -Mode create-pr -ConfigFile $f.Config -SkipFetch -GitHubAdapter {param($a,$d)$script:GitHubActions+=$a};Assert-Equal $r.Risk 'HIGH';Assert-Equal $r.FinalStatus 'stopped';Assert-True($script:GitHubActions-notcontains'push')}
  Test-Case 'integration duplicate execution protection'{$f=New-Fixture 'duplicate';$first=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;$second=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;Assert-Equal $first.FinalStatus 'validated' $first.StopReason;Assert-Equal $second.FinalStatus 'stopped';Assert-True($second.StopReason-match'completed checkpoint')}
  Test-Case 'integration resume and cleanup'{$f=New-Fixture 'resume';$first=Invoke-ForeverOperator -TaskFile $f.Task -Mode validate-only -ConfigFile $f.Config -SkipFetch;$second=Invoke-ForeverOperator -TaskFile $f.Task -Mode resume -ConfigFile $f.Config -SkipFetch;Assert-Equal $second.FinalStatus 'validated' $second.StopReason;$clean=Invoke-ForeverOperator -TaskFile $f.Task -Mode cleanup -ConfigFile $f.Config -SkipFetch;Assert-Equal $clean.FinalStatus 'cleaned'}
  Test-Case 'automatic merge rejects stale SHA and missing checks'{$report=[pscustomobject]@{Risk='LOW';Commit='a'*40};$task=[pscustomobject]@{allowAutomaticMerge=$true;branchName='factory/x'};$config=[pscustomobject]@{autoMerge=$true;defaultBranch='main'};$pr=[pscustomobject]@{baseRefName='main';headRefName='factory/x';headRefOid='b'*40;mergeable='MERGEABLE';reviewDecision='APPROVED';statusCheckRollup=@()};$e=Test-AutomaticMergeEligibility $report $task $config $pr $null;Assert-True(-not$e.Eligible);Assert-True(($e.Reasons-join' ') -match'SHA');Assert-True(($e.Reasons-join' ') -match'checks')}
}finally{if(Test-Path -LiteralPath $script:Root){Remove-Item -LiteralPath $script:Root -Recurse -Force}}
Write-Host "`n$script:Passed passed; $script:Failed failed";if($script:Failed){exit 1}
