/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as InternalCoralinaRouteImport } from './routes/internal.coralina'
import { Route as AdvisoryReportRouteImport } from './routes/advisory_.report'
import { Route as InternalProjectsSlugRouteImport } from './routes/internal.projects.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalCoralinaRoute = InternalCoralinaRouteImport.update({
  id: '/internal/coralina',
  path: '/internal/coralina',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryReportRoute = AdvisoryReportRouteImport.update({
  id: '/advisory_/report',
  path: '/advisory/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalProjectsSlugRoute = InternalProjectsSlugRouteImport.update({
  id: '/internal/projects/$slug',
  path: '/internal/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/areas': typeof AreasRoute
  '/booth': typeof BoothRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/navigator': typeof NavigatorRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/advisory/report': typeof AdvisoryReportRoute
  '/internal/coralina': typeof InternalCoralinaRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/internal/projects/$slug': typeof InternalProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/areas': typeof AreasRoute
  '/booth': typeof BoothRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/navigator': typeof NavigatorRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/advisory/report': typeof AdvisoryReportRoute
  '/internal/coralina': typeof InternalCoralinaRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/internal/projects/$slug': typeof InternalProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/areas': typeof AreasRoute
  '/booth': typeof BoothRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/navigator': typeof NavigatorRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/advisory_/report': typeof AdvisoryReportRoute
  '/internal/coralina': typeof InternalCoralinaRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/internal/projects/$slug': typeof InternalProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/areas'
    | '/booth'
    | '/contact'
    | '/discovery'
    | '/navigator'
    | '/offers'
    | '/reviews'
    | '/sitemap.xml'
    | '/advisory/report'
    | '/internal/coralina'
    | '/projects/$slug'
    | '/projects/'
    | '/internal/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/areas'
    | '/booth'
    | '/contact'
    | '/discovery'
    | '/navigator'
    | '/offers'
    | '/reviews'
    | '/sitemap.xml'
    | '/advisory/report'
    | '/internal/coralina'
    | '/projects/$slug'
    | '/projects'
    | '/internal/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/areas'
    | '/booth'
    | '/contact'
    | '/discovery'
    | '/navigator'
    | '/offers'
    | '/reviews'
    | '/sitemap.xml'
    | '/advisory_/report'
    | '/internal/coralina'
    | '/projects/$slug'
    | '/projects/'
    | '/internal/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  AreasRoute: typeof AreasRoute
  BoothRoute: typeof BoothRoute
  ContactRoute: typeof ContactRoute
  DiscoveryRoute: typeof DiscoveryRoute
  NavigatorRoute: typeof NavigatorRoute
  OffersRoute: typeof OffersRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdvisoryReportRoute: typeof AdvisoryReportRoute
  InternalCoralinaRoute: typeof InternalCoralinaRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  InternalProjectsSlugRoute: typeof InternalProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/coralina': {
      id: '/internal/coralina'
      path: '/internal/coralina'
      fullPath: '/internal/coralina'
      preLoaderRoute: typeof InternalCoralinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory_/report': {
      id: '/advisory_/report'
      path: '/advisory/report'
      fullPath: '/advisory/report'
      preLoaderRoute: typeof AdvisoryReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/projects/$slug': {
      id: '/internal/projects/$slug'
      path: '/internal/projects/$slug'
      fullPath: '/internal/projects/$slug'
      preLoaderRoute: typeof InternalProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  AreasRoute: AreasRoute,
  BoothRoute: BoothRoute,
  ContactRoute: ContactRoute,
  DiscoveryRoute: DiscoveryRoute,
  NavigatorRoute: NavigatorRoute,
  OffersRoute: OffersRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdvisoryReportRoute: AdvisoryReportRoute,
  InternalCoralinaRoute: InternalCoralinaRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  InternalProjectsSlugRoute: InternalProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
