-- FDB-001: Safe seed for the first canonical project record.
-- Seed only: Developer Title, Location Bang Tao, Project Modeva.

WITH developer_seed AS (
  INSERT INTO public.developers (
    slug,
    name,
    legal_name,
    description,
    country,
    headquarters_location,
    verification_status,
    last_verified_at
  )
  VALUES (
    'title',
    'Title',
    'Title',
    'Developer record for Modeva.',
    'Thailand',
    'Phuket, Thailand',
    'verified',
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    legal_name = EXCLUDED.legal_name,
    description = EXCLUDED.description,
    country = EXCLUDED.country,
    headquarters_location = EXCLUDED.headquarters_location,
    verification_status = EXCLUDED.verification_status,
    last_verified_at = EXCLUDED.last_verified_at,
    updated_at = now()
  RETURNING id
),
location_seed AS (
  INSERT INTO public.locations (
    slug,
    area_name,
    country,
    province,
    district,
    description,
    market_summary,
    lifestyle_summary
  )
  VALUES (
    'bang-tao',
    'Bang Tao',
    'Thailand',
    'Phuket',
    'Thalang',
    'Bang Tao is a west-coast Phuket area with beach access, lifestyle amenities, and strong buyer demand.',
    'Established Phuket lifestyle and investment area with active residential demand.',
    'Beach, dining, wellness, retail, and family-oriented services around the Laguna corridor.'
  )
  ON CONFLICT (slug) DO UPDATE SET
    area_name = EXCLUDED.area_name,
    country = EXCLUDED.country,
    province = EXCLUDED.province,
    district = EXCLUDED.district,
    description = EXCLUDED.description,
    market_summary = EXCLUDED.market_summary,
    lifestyle_summary = EXCLUDED.lifestyle_summary,
    updated_at = now()
  RETURNING id
),
resolved_seed AS (
  SELECT
    (SELECT id FROM developer_seed) AS developer_id,
    (SELECT id FROM location_seed) AS location_id
)
INSERT INTO public.projects (
  developer_id,
  location_id,
  project_code,
  name,
  slug,
  project_type,
  location_area,
  address,
  short_description,
  full_description,
  construction_status,
  ownership_type,
  distance_to_beach,
  is_featured,
  is_active,
  public_status,
  sales_status,
  tagline,
  highlights,
  trust_score,
  trust_note,
  investment_value,
  market_position,
  verdict,
  starting_price_thb,
  price_range,
  last_price_update,
  beds_display,
  area_range,
  verified_price,
  rental_demand,
  start_date_display,
  completion_date_display,
  last_inspection,
  forever_verified,
  verified_at,
  last_data_review_at
)
SELECT
  developer_id,
  location_id,
  'MODEVA',
  'Modeva',
  'modeva',
  'Condominium',
  'Bang Tao',
  'Bang Tao, Phuket, Thailand',
  'Verified Bang Tao project reviewed through the Forever decision framework.',
  'Modeva is the first canonical seed project in the Forever Core Database foundation.',
  'Planning',
  'Freehold',
  'Bang Tao area',
  true,
  true,
  'published',
  'Available',
  'Verified Bang Tao project reviewed through the Forever decision framework.',
  ARRAY['Forever Verified project record', 'Bang Tao location', 'Structured project foundation'],
  0,
  'Awaiting full Forever inspection data.',
  0,
  'Under review',
  'Under Review',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  'Under review',
  '',
  '',
  '',
  true,
  now(),
  now()
FROM resolved_seed
ON CONFLICT (slug) DO UPDATE SET
  developer_id = EXCLUDED.developer_id,
  location_id = EXCLUDED.location_id,
  project_code = EXCLUDED.project_code,
  name = EXCLUDED.name,
  project_type = EXCLUDED.project_type,
  location_area = EXCLUDED.location_area,
  address = EXCLUDED.address,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  construction_status = EXCLUDED.construction_status,
  ownership_type = EXCLUDED.ownership_type,
  distance_to_beach = EXCLUDED.distance_to_beach,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active,
  public_status = EXCLUDED.public_status,
  sales_status = EXCLUDED.sales_status,
  tagline = EXCLUDED.tagline,
  highlights = EXCLUDED.highlights,
  trust_score = EXCLUDED.trust_score,
  trust_note = EXCLUDED.trust_note,
  investment_value = EXCLUDED.investment_value,
  market_position = EXCLUDED.market_position,
  verdict = EXCLUDED.verdict,
  starting_price_thb = EXCLUDED.starting_price_thb,
  price_range = EXCLUDED.price_range,
  last_price_update = EXCLUDED.last_price_update,
  beds_display = EXCLUDED.beds_display,
  area_range = EXCLUDED.area_range,
  verified_price = EXCLUDED.verified_price,
  rental_demand = EXCLUDED.rental_demand,
  start_date_display = EXCLUDED.start_date_display,
  completion_date_display = EXCLUDED.completion_date_display,
  last_inspection = EXCLUDED.last_inspection,
  forever_verified = EXCLUDED.forever_verified,
  verified_at = EXCLUDED.verified_at,
  last_data_review_at = EXCLUDED.last_data_review_at,
  updated_at = now();
